name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: 'sparkfun:apollo3:redboard_artemis'
          sketch-paths: |
            - ./
          platforms: |
            - source-url: "https://github.com/sparkfun/Arduino_Apollo3.git"
            - name: "sparkfun:apollo3"
          libraries: |
            - source-url: "https://github.com/sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library.git"